development:
  adapter: postgresql
  encoding: unicode
  database: fly_china_market_development
  pool: 5
  username: <%=  ENV['database_username'] %>
  password: <%= ENV['database_password'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: fly_china_market_test
  pool: 5
  username: <%=  ENV['database_username'] %>
  password: <%= ENV['database_password'] %>
production:
  adapter: postgresql
  encoding: unicode
  database: fly_china_market_production
  pool: 5
  username: <%=  ENV['database_username'] %>
  password: <%= ENV['database_password'] %>
